### ISSUE TITLE
Is this library only for read requests?

### ISSUE THREAD

**Issue by vimmerru** [hyperledger/indy-vdr#51]
Hi,

Do you have any plans to support posting nyms, cred defs and other transactions to Indy registry?

**Comment by swcurran** [comment]
No. The library supports all of the same posting transactions as the indy-sdk.

**Comment by vimmerru** [comment]
@swcurran Do you have any example/documentation about this?

**Comment by swcurran** [comment]
The documentation is not great yet -- we'll be working on that.  But easiest is probably to spin up a VON Network and use the [Proxy Server](https://github.com/hyperledger/indy-vdr#proxy-server) to POST to the /submit endpoint indy-node transactions.

**Comment by vimmerru** [comment]
@swcurran Thanks! I went through the code and got better understanding.

**Comment by pstuermlinger** [comment]
> The documentation is not great yet -- we'll be working on that. But easiest is probably to spin up a VON Network and use the [Proxy Server](https://github.com/hyperledger/indy-vdr#proxy-server) to POST to the /submit endpoint indy-node transactions.

Hi Stephen, does this mean someone can create and sign a transaction, then post it to `/submit` of indy-vdr and then indy-vdr will forward it to the nodes so that this transaction can be written to the ledger?

And in general: how does indy-vdr know which ledger to contact if it's connected to multiple ones?

**Comment by swcurran** [comment]
Hi @pstuermlinger 

> Hi Stephen, does this mean someone can create and sign a transaction, then post it to /submit of indy-vdr and then indy-vdr will forward it to the nodes so that this transaction can be written to the ledger?

Yes.  This is not just a read only module, it allows writing to a ledger.  Our team has a branch under Aries Cloud Agent Python that uses indy-vdr instead of indy-sdk to handle all writing.

> And in general: how does indy-vdr know which ledger to contact if it's connected to multiple ones?

At the moment it doesn't -- it spins up and connects to one Indy pool (network instance) using a genesis file for that ledger and operates on that network.  That needs to expand.  In the short term, we might do what LISSI has done and have the component connect to several ledgers and try each one as needed.  That would be invisible to the caller, but is very inefficient and with the current "did:sov" method could result in the same object resolving to different networks.

The better answer comes with some Hyperledger Indy work that is happening now to define a new "did:indy" method that includes in the DID an identifier for that network (e.g. `did:indy:sovrin:12323241234`)  In that, indy-vdr (and indy-sdk) will know exactly what network to use and can make a policy choice of resolving a DID or not based on the network on which the DID resides.

**Comment by pstuermlinger** [comment]
Thank you @swcurran for this very valuable reply!

So, once vdr supports multi-ledger read by "brute-forcing" ledgers until it receives an answer to the request, will this also affect the `/submit` endpoint? I assume the transaction author needs a way to tell to which ledger the transaction has to be written to?

> The better answer comes with some Hyperledger Indy work that is happening now to define a new "did:indy" method that includes in the DID an identifier for that network (e.g. did:indy:sovrin:12323241234) In that, indy-vdr (and indy-sdk) will know exactly what network to use and can make a policy choice of resolving a DID or not based on the network on which the DID resides.

I already noticed this in the code of the [did-sov driver](https://github.com/decentralized-identity/uni-resolver-driver-did-sov/blob/90000dfdb013866b5a334416a213792bb4d61320/src/main/java/uniresolver/driver/did/sov/DidSovDriver.java#L134) for [Universal Resolver](https://github.com/decentralized-identity/universal-resolver). It uses the same/similar scheme for DID parsing as you did: `did:method:network:12345`.
This scheme, however, seems to be different from the proposed `Namespace Specific Identifiers` at the Editor's Draft, which uses a scheme like `did:method:12345:faber-staging`.
If you know about any place where this is discussed, I'd appreciate a link to follow this topic.

Thanks again!

**Comment by swcurran** [comment]
Wow...that is really interesting.  After all these years of working with Indy and Sovrin, I never knew, nor had anyone mention about the trailing namespace.  AFAIK -- I don't think it has been implemented anywhere, nor is there a mechanism to go from namespace to network instance.

The work on the `did:indy` method is happening here: https://wiki.hyperledger.org/display/indy/Indy+DID+Method+Specification

The current draft spec is here: https://hackmd.io/@icZC4epNSnqBbYE0hJYseA/S1eUS2BQw
